services:
  - type: web
    name: searchpilot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python start_render.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.6
